config/routes.rb
Rails.application.routes.draw do
  
   get 'feed', to: 'feed#show'
  
   resources :users, only: :show, param: :username do
    member do
      post 'follow', to: 'follows#create'
      delete 'unfollow', to: 'follows#destroy'
    end
  end


  resources :runs
  resources :tweets
  ActiveAdmin.routes(self)
  devise_for :users
  as :user do
  	get "signin" => 'devise/sessions#new'
  	delete "signout" => 'devise/sessions#destroy'
  	get "signup" => 'devise/registrations#new'
  end
  root "pages#home"
  get 'about' => 'pages#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_authorization.rb
class AdminAuthorization < ActiveAdmin::AuthorizationAdapter

def authorized?(action, subject = nil)
	user && user.admin?
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/run.rb
class Run < ApplicationRecord
  belongs_to :user

  validates :user, presence:true
  validates :Run_Type, presence:true
  validates :Location, presence:true
  validates :Start_Time, presence:true
  validates :Pace, presence:true, length: {maximum: 5}
  validates :Miles, presence:true, length: {maximum: 5}
  validates :Run_Date, presence:true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_many :tweets
  has_many :runs

  validates :username, presence: true, uniqueness: true, length: {minimum: 6}
  validates :name, presence: true

  acts_as_followable
  acts_as_follower
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery with: :exception
before_action :configure_permitted_parameters, if: :devise_controller?
	

	def access_denied(exception)
		redirect_to root_path, alert: exception.message
	end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name])
  end

end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  def show
  
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!

  def create
    user = User.find_by(username: params[:username])
    Follow.create(followable: user, follower: current_user)
    redirect_to user_path(user.username), notice: "Successfully followed user"
  end

  def destroy
    user = User.find_by(username: params[:username])
    Follow.find_by(followable: user, follower: current_user).destroy
    redirect_to user_path(user.username), notice: "Successfully unfollowed user"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  # GET /runs
  # GET /runs.json
  def index
    @runs = Run.all
  end

  # GET /runs/1
  # GET /runs/1.json
  def show
     @run = Run.find(params[:id])
  end

  # GET /runs/new
  def new
    @run = current_user.runs.new
  end

  # GET /runs/1/edit
  def edit
      @run = current_user.runs.find(params[:id])
  end

  # POST /runs
  # POST /runs.json
   def create
    @run = current_user.runs.new(run_params)
    if @run.save
      redirect_to @run, notice: 'Run was successfully created.'
    else
      render :new 
    end
  end

  # PATCH/PUT /runs/1
  # PATCH/PUT /runs/1.json
def update
    @run = current_user.runs.find(params[:id])
    if @run.update(run_params)
      redirect_to @run, notice: 'Run was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /runs/1
  # DELETE /runs/1.json
   def destroy
    @run = current_user.runs.find(params[:id])
    @run.destroy
    redirect_to runs_url, notice: 'Run was successfully deleted.'
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_run
      @run = Run.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def run_params
      params.require(:run).permit(:user_id, :Run_Type, :Location, :Start_Time, :Pace, :Miles, :Run_Date)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  # GET /tweets
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  def show
    @tweet = Tweet.find(params[:id])
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.new
  end

  # GET /tweets/1/edit
  def edit
    @tweet = current_user.tweets.find(params[:id])
  end

  # POST /tweets
  def create
    @tweet = current_user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to @tweet, notice: 'Tweet was successfully created.'
    else
      render :new 
    end
  end

  # PATCH/PUT /tweets/1
  def update
    @tweet = current_user.tweets.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: 'Tweet was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet = current_user.tweets.find(params[:id])
    @tweet.destroy
    redirect_to tweets_url, notice: 'Tweet was successfully destroyed.'
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:content, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
     @user = User.find_by(username: params[:username])
     @runs = @user.runs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/Feed/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="card card-block">
        <h4 class="card-title">Your Account</h4>
        <p class="card-text"><%= link_to current_user.username, user_path(current_user.username) %></p>
      </div>
    </div>
    <div class="col-md-8">
      <% if user_signed_in? %>
        <center><%= link_to 'New Tweet', new_run_path %></center>
      <% end %>
      <ul class="list-group">
        <% @runs.each do |run| %>
          <%= link_to run, class: "list-group-item list-group-item-action" do %>
            <h5 class="list-group-item-heading"><%= run.user.username %></h5>
            <p class="list-group-item-text"><%= run.content %></p>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AktivPal</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://www.gstatic.com/firebasejs/5.8.2/firebase.js"></script>
<script>
  // Initialize Firebase
  var config = {
    apiKey: "AIzaSyB1d4rO1SwFzeFMBztDcg4t1qBKxudy7Lc",
    authDomain: "aktivpal-21d37.firebaseapp.com",
    databaseURL: "https://aktivpal-21d37.firebaseio.com",
    projectId: "aktivpal-21d37",
    storageBucket: "aktivpal-21d37.appspot.com",
    messagingSenderId: "751710851613"
  };
  firebase.initializeApp(config);
</script>
  </head>

  <body>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Navigation Bar -->
     <nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container">
    <%= link_to "AktivPal", root_path, class: "navbar-brand" %>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "View Runs", runs_path, class: "nav-link" %></li>
    </ul>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item"><%= link_to "Log out", signout_path, method: :delete, class: "nav-link" %></li>
      <% else %>
        <li class="nav-item"><%= link_to "Sign in", signin_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Sign up", signup_path, class: "btn btn-primary" %></li>
      <% end %>
    </ul>
  </div>
    </nav>

<!-- Flash Messages -->
<% flash.each do |name, message|%>
  <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
<% end %>

    <!-- Page Content -->
    <%= yield %>
    
    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>AktivPal © 2019</p>
        </center>
      </div>
    </footer>

  </body>
</html>

app/views/pages/home.html.erb
<% if user_signed_in? %>
    <div class="jumbotron jumbotron-home">
            <div class="container">
                <h1>Welcome back!</h1>
            </div>
    </div>
 <% else %>
        <div class="jumbotron jumbotron-home">
            <div class="container">
    
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <h2>Post Runs</h2>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                    <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
                </div>
                <div class="col-md-4">
                    <h2>Join Runs</h2>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                    <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
                </div>
                <div class="col-md-4">
                    <h2>Workout Together</h2>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                    <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
                </div>
            </div>
        </div>

 <% end %>

app/views/runs/_form.html.erb
<%= form_with(model: run, local: true) do |form| %>
  <% if run.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(run.errors.count, "error") %> prohibited this run from being saved:</h2>

      <ul>
      <% run.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



    <div class="form-group">
    <%= form.label :Run_Type %>
    <%= form.text_field :Run_Type, class: "form-control" %>
    </div>

   <div class="form-group">
    <%= form.label :Location %>
    <%= form.text_field :Location, class: "form-control" %>
   </div>

  <div class="form-group">
    <%= form.label :Run_Date %>
    <%= form.date_select :Run_Date, class: "form-control" %>
    </div>

   <div class="form-group">
    <%= form.label :Start_Time %>
    <%= form.time_select :Start_Time, class: "form-control" %>
    </div>

  <div class="form-group">
    <%= form.label :Pace %>
    <%= form.text_field :Pace, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :Miles %>
    <%= form.text_field :Miles, class: "form-control" %>
  </div>

 <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/runs/edit.html.erb
<div class="container">

		<h1>Editing Run</h1>

		<%= render 'form', run: @run %>

		<%= link_to 'Show', @run %> |
		<%= link_to 'Back', runs_path %>
</div>

app/views/runs/index.html.erb
<div class="container">

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Ready.Set.Go.</h1>
    <p class="lead">Create a Run | Discover a run near you</p>
        
  </div>
</div>

   <% if user_signed_in? %>
              <%= link_to '+ New Run', new_run_path, class: "btn btn-primary" %>

           
<% end %>


<P>
  <div class="col-md-12">
  <table class="table">
          <thead>
            <tr>
              <th>User</th>
              <th>Run Type</th>
              <th>Location</th>
              <th>Start Time</th>
              <th>Pace</th>
              <th>Miles</th>
              <th>Date</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @runs.each do |run| %>
                <td><%= run.user.try(:username) %></td>
                <td><%= run.Run_Type %></td>
                <td><%= run.Location %></td>
                <td><%= run.Start_Time %></td>
                <td><%= run.Pace %></td>
                <td><%= run.Miles %></td>
                <td><%= run.Run_Date %></td>
                <td><%= link_to 'Join Run', run %></td>
                <% if run.user == current_user %>
                <td><%= link_to 'Edit Run', edit_run_path(run) %></td> 
                <td><%= link_to 'Delete Run', run, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                 <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>

        <br>
         
</div>

app/views/runs/new.html.erb
<div class="container">
	<h1>New Run</h1>

	<%= render 'form', run: @run %>

	<%= link_to 'Back', runs_path %>
</div>

app/views/runs/show.html.erb
<div class="container">
  <div class="card">
  <div class="card-body">
    <p>
        <strong>User:</strong>
        <%= link_to @run.user.username, user_path(@run.user.username) %>
      </p>

      <p>
        <strong>Run Type:</strong>
        <%= @run.Run_Type %>
      </p>

      <p>
        <strong>Location:</strong>
        <%= @run.Location %>
      </p>

      <p>
        <strong>Start time:</strong>
        <%= @run.Start_Time %>
      </p>

      <p>
        <strong>Run Date:</strong>
        <%= @run.Run_Date %>
      </p>
      <p>
        <strong>Pace:</strong>
        <%= @run.Pace %>
      </p>

      <p>
        <strong>Miles:</strong>
        <%= @run.Miles %>
      </p>

      <% if @run.user == current_user %>
      <%= link_to 'Edit', edit_run_path(@run), class: "card-link" %> |
       <%= link_to 'Delete', @run, method: :delete, data: { confirm: 'Are you sure?' } %> |
      <% end %>
      <%= link_to 'Back', runs_path %>
</div>
</div>       
</div>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<div class="container">
	<h1>Editing Tweet</h1>

	<%= render 'form', tweet: @tweet %>

	<%= link_to 'Show', @tweet %> |
	<%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/index.html.erb
<div class="container">
        <h1>Tweets</h1>

        <table class="table">
          <thead>
            <tr>
              <th>User</th>
              <th>Content</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @tweets.each do |tweet| %>
              <tr>
                <td><%= tweet.user.try(:email) %></td>
                <td><%= tweet.content %></td>
                <td><%= link_to 'Show', tweet %></td>
                <% if tweet.user == current_user %>
                    <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
                    <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>

        <br>
        <% if user_signed_in? %>
            <%= link_to 'New Tweet', new_tweet_path %>
        <% end %>
</div>

app/views/tweets/new.html.erb
<div class="container">
	<h1>New Tweet</h1>

	<%= render 'form', tweet: @tweet %>

	<%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/show.html.erb
<div class="container">
			<p>
			  <strong>User:</strong>
			  <%= @tweet.user %>
			</p>

			<p>
			  <strong>Content:</strong>
			  <%= @tweet.content %>
			</p>
			<% if @tweet.user == current_user %>
				<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
			<% end %>
			<%= link_to 'Back', tweets_path %>
</div>

app/views/users/show.html.erb
<% if user_signed_in? %>

              <div class="container">
              		<h1><%= @user.username %></h1>
              		<p><%= @user.name %></p>

              </div>


              <P>
                <div class="col-md-12">
                <table class="table">
                        <thead>
                          <tr>
                            <th>User</th>
                            <th>Run Type</th>
                            <th>Location</th>
                            <th>Start Time</th>
                            <th>Pace</th>
                            <th>Miles</th>
                            <th>Date</th>
                            <th colspan="3"></th>
                          </tr>
                        </thead>

                        <tbody>
                          <% @runs.each do |run| %>
                              <td><%= run.user.try(:username) %><p> 
                                <% if current_user.following?(@user) %> 
                                <%= link_to "Unfollow", unfollow_user_path(@user.username), method: :delete %></p>
                                <% else %>  
                                <%= link_to "Follow", follow_user_path(@user.username), method: :post %> </td> 
                                <% end %>
                              <td><%= run.Run_Type %></td>
                              <td><%= run.Location %></td>
                              <td><%= run.Start_Time %></td>
                              <td><%= run.Pace %></td>
                              <td><%= run.Miles %></td>
                              <td><%= run.Run_Date %></td>
                              <td><%= link_to 'Show', run %></td>
                              <% if run.user == current_user %>
                              <td><%= link_to 'Edit', edit_run_path(run) %></td> 
                              <td><%= link_to 'Destroy', run, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                               <% end %>
                            </tr>
                          <% end %>
                        </tbody>
                      </table>

                      <br>
                       
              </div>

              <% else %>
<div class="container">
  <P>
<p align="center">User profiles cannot be viewed without signing in!</p>

</div>
        <% end %>